// <auto-generated />
using System;
using AWork.Candidates.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AWork.Infra.Migrations
{
    [DbContext(typeof(CandidateContext))]
    [Migration("20210226145740_PersonUserId")]
    partial class PersonUserId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AWork.Business.Models.AcademicEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CourseStatus")
                        .HasColumnType("int");

                    b.Property<string>("CustomCourse")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PersonId");

                    b.ToTable("AcademicEducations");
                });

            modelBuilder.Entity("AWork.Business.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AWork.Business.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("WorkingHours")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AWork.Business.Models.ContractRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalyzedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedById");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractRequests");
                });

            modelBuilder.Entity("AWork.Business.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AWork.Business.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLevelId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AWork.Business.Models.CourseLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseLevelName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CourseLevels");
                });

            modelBuilder.Entity("AWork.Business.Models.Entities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("EntitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntityChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SiteAddress")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SiteDomain")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("UseWebServer_GrupoAPSe")
                        .HasColumnType("bit");

                    b.Property<int?>("WebServer_GrupoAPSe_Id_Empresa")
                        .HasColumnType("int");

                    b.Property<string>("WebServer_GrupoAPSe_password")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("WebServer_GrupoAPSe_user")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntitiesId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("AWork.Business.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<byte[]>("FileStream")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("AWork.Business.Models.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Attachment")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IndicationName")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("InterviewStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterviewsScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterviewStatusId");

                    b.HasIndex("InterviewsScheduleId")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("AWork.Business.Models.InterviewStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("InterviewStatus");
                });

            modelBuilder.Entity("AWork.Business.Models.InterviewsSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("JobSubscribeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Via")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobSubscribeId");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("InterviewsSchedules");
                });

            modelBuilder.Entity("AWork.Business.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("JobQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("JobRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JobRequestId")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("AWork.Business.Models.JobRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("JobQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JobTitleId")
                        .IsUnique();

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("JobRequests");
                });

            modelBuilder.Entity("AWork.Business.Models.JobRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalyzedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("JobRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedById");

                    b.HasIndex("JobRequestId");

                    b.ToTable("JobRequestStatus");
                });

            modelBuilder.Entity("AWork.Business.Models.JobSubscribe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("PersonId");

                    b.ToTable("JobSubscribes");
                });

            modelBuilder.Entity("AWork.Business.Models.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("AWork.Business.Models.JobTitleInterested", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("PersonId");

                    b.ToTable("JobTitleInteresteds");
                });

            modelBuilder.Entity("AWork.Business.Models.JobTitleLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("JobTitleLevels");
                });

            modelBuilder.Entity("AWork.Business.Models.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("AWork.Business.Models.LanguagePerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanguageLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PersonId");

                    b.ToTable("LanguegePerson");
                });

            modelBuilder.Entity("AWork.Business.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("EntityId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AWork.Business.Models.MaritalStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatus");
                });

            modelBuilder.Entity("AWork.Business.Models.NotificationForPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AWork.Business.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("DownloadPPD")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .HasColumnType("varchar(450)");

                    b.Property<int?>("GrupoAPSeIdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdGroupApse")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdGroupApseGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("MaritalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NationalityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PPD")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReligionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecialNeedsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("SpecialNeedsId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AWork.Business.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PhoneType")
                        .HasColumnType("int");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("AWork.Business.Models.ProfessionalBackground", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CurrentJob")
                        .HasColumnType("bit");

                    b.Property<string>("DescriptionJob")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobTitleLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobTitleName")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkingAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleLevelId");

                    b.HasIndex("PersonId");

                    b.HasIndex("WorkingAreaId");

                    b.ToTable("ProfessionalBackgrounds");
                });

            modelBuilder.Entity("AWork.Business.Models.Religion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("AWork.Business.Models.SpecialNeeds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SpecialNeeds");
                });

            modelBuilder.Entity("AWork.Business.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("AWork.Business.Models.SyncAPS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResignationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.ToTable("SyncAPS");
                });

            modelBuilder.Entity("AWork.Business.Models.WorkingArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("WorkingAreas");
                });

            modelBuilder.Entity("AWork.Business.Models.Candidate", b =>
                {
                    b.HasBaseType("AWork.Business.Models.Person");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("AWork.Business.Models.AcademicEducation", b =>
                {
                    b.HasOne("AWork.Business.Models.Course", "Course")
                        .WithMany("AcademicEducations")
                        .HasForeignKey("CourseId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Person", "Person")
                        .WithMany("AcademicEducations")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AWork.Business.Models.Address", b =>
                {
                    b.HasOne("AWork.Business.Models.Country", "Country")
                        .WithMany("Address")
                        .HasForeignKey("CountryId")
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AWork.Business.Models.Contract", b =>
                {
                    b.HasOne("AWork.Business.Models.Interview", "Interview")
                        .WithOne("Contract")
                        .HasForeignKey("AWork.Business.Models.Contract", "InterviewId")
                        .IsRequired();

                    b.Navigation("Interview");
                });

            modelBuilder.Entity("AWork.Business.Models.ContractRequest", b =>
                {
                    b.HasOne("AWork.Business.Models.Person", "AnalyzedBy")
                        .WithMany("ContractRequests")
                        .HasForeignKey("AnalyzedById")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Contract", "Contract")
                        .WithMany("ContractRequests")
                        .HasForeignKey("ContractId")
                        .IsRequired();

                    b.Navigation("AnalyzedBy");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AWork.Business.Models.Course", b =>
                {
                    b.HasOne("AWork.Business.Models.CourseLevel", "CourseLevel")
                        .WithMany("Course")
                        .HasForeignKey("CourseLevelId")
                        .IsRequired();

                    b.Navigation("CourseLevel");
                });

            modelBuilder.Entity("AWork.Business.Models.Entities", b =>
                {
                    b.HasOne("AWork.Business.Models.Entities", null)
                        .WithMany("EntityChild")
                        .HasForeignKey("EntitiesId");
                });

            modelBuilder.Entity("AWork.Business.Models.Interview", b =>
                {
                    b.HasOne("AWork.Business.Models.InterviewStatus", "InterviewStatus")
                        .WithMany("Interviews")
                        .HasForeignKey("InterviewStatusId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.InterviewsSchedule", "InterviewsSchedule")
                        .WithOne("Interview")
                        .HasForeignKey("AWork.Business.Models.Interview", "InterviewsScheduleId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Person", null)
                        .WithMany("Interviews")
                        .HasForeignKey("PersonId");

                    b.Navigation("InterviewsSchedule");

                    b.Navigation("InterviewStatus");
                });

            modelBuilder.Entity("AWork.Business.Models.InterviewsSchedule", b =>
                {
                    b.HasOne("AWork.Business.Models.JobSubscribe", "JobSubscribe")
                        .WithMany("InterviewsSchedules")
                        .HasForeignKey("JobSubscribeId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Location", "Location")
                        .WithOne("InterviewsSchedule")
                        .HasForeignKey("AWork.Business.Models.InterviewsSchedule", "LocationId")
                        .IsRequired();

                    b.Navigation("JobSubscribe");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AWork.Business.Models.Job", b =>
                {
                    b.HasOne("AWork.Business.Models.Person", "CreatedBy")
                        .WithMany("Jobs")
                        .HasForeignKey("CreatedById")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.JobRequest", "JobRequest")
                        .WithOne("Job")
                        .HasForeignKey("AWork.Business.Models.Job", "JobRequestId")
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("AWork.Business.Models.JobRequest", b =>
                {
                    b.HasOne("AWork.Business.Models.Person", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.JobTitle", "JobTitle")
                        .WithOne("JobRequest")
                        .HasForeignKey("AWork.Business.Models.JobRequest", "JobTitleId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Location", "Location")
                        .WithOne("JobRequest")
                        .HasForeignKey("AWork.Business.Models.JobRequest", "LocationId")
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("JobTitle");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AWork.Business.Models.JobRequestStatus", b =>
                {
                    b.HasOne("AWork.Business.Models.Person", "AnalyzedBy")
                        .WithMany("JobRequestStatus")
                        .HasForeignKey("AnalyzedById")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.JobRequest", "JobRequest")
                        .WithMany("JobRequestStatus")
                        .HasForeignKey("JobRequestId")
                        .IsRequired();

                    b.Navigation("AnalyzedBy");

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("AWork.Business.Models.JobSubscribe", b =>
                {
                    b.HasOne("AWork.Business.Models.Job", "Job")
                        .WithMany("JobSubscribe")
                        .HasForeignKey("JobId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Person", "Person")
                        .WithMany("JobSubscribes")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AWork.Business.Models.JobTitle", b =>
                {
                    b.HasOne("AWork.Business.Models.JobTitle", "JobTitleParent")
                        .WithMany("JobTitleChild")
                        .HasForeignKey("JobTitleId");

                    b.Navigation("JobTitleParent");
                });

            modelBuilder.Entity("AWork.Business.Models.JobTitleInterested", b =>
                {
                    b.HasOne("AWork.Business.Models.JobTitle", "JobTitle")
                        .WithMany("JobTitleInteresteds")
                        .HasForeignKey("JobTitleId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Person", "Person")
                        .WithMany("JobTitleInteresteds")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.Navigation("JobTitle");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AWork.Business.Models.LanguagePerson", b =>
                {
                    b.HasOne("AWork.Business.Models.Language", "Language")
                        .WithMany("Languages")
                        .HasForeignKey("LanguageId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Person", "Person")
                        .WithMany("Languages")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AWork.Business.Models.Location", b =>
                {
                    b.HasOne("AWork.Business.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Entities", "Entity")
                        .WithMany("Locations")
                        .HasForeignKey("EntityId")
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("AWork.Business.Models.NotificationForPerson", b =>
                {
                    b.HasOne("AWork.Business.Models.Person", "Person")
                        .WithMany("Notifications")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AWork.Business.Models.Person", b =>
                {
                    b.HasOne("AWork.Business.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("AWork.Business.Models.MaritalStatus", "MaritalStatus")
                        .WithMany("People")
                        .HasForeignKey("MaritalStatusId");

                    b.HasOne("AWork.Business.Models.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("AWork.Business.Models.Religion", "Religion")
                        .WithMany("People")
                        .HasForeignKey("ReligionId");

                    b.HasOne("AWork.Business.Models.SpecialNeeds", "SpecialNeeds")
                        .WithMany("People")
                        .HasForeignKey("SpecialNeedsId");

                    b.Navigation("Address");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Nationality");

                    b.Navigation("Religion");

                    b.Navigation("SpecialNeeds");
                });

            modelBuilder.Entity("AWork.Business.Models.Phone", b =>
                {
                    b.HasOne("AWork.Business.Models.Person", "Person")
                        .WithMany("Phones")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AWork.Business.Models.ProfessionalBackground", b =>
                {
                    b.HasOne("AWork.Business.Models.JobTitleLevel", "JobTitleLevel")
                        .WithMany("ProfessionalBackgrounds")
                        .HasForeignKey("JobTitleLevelId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.Person", "Person")
                        .WithMany("ProfessionalBackgrounds")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.HasOne("AWork.Business.Models.WorkingArea", "WorkingArea")
                        .WithMany("ProfessionalBackgrounds")
                        .HasForeignKey("WorkingAreaId")
                        .IsRequired();

                    b.Navigation("JobTitleLevel");

                    b.Navigation("Person");

                    b.Navigation("WorkingArea");
                });

            modelBuilder.Entity("AWork.Business.Models.Candidate", b =>
                {
                    b.HasOne("AWork.Business.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("AWork.Business.Models.Candidate", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AWork.Business.Models.Contract", b =>
                {
                    b.Navigation("ContractRequests");
                });

            modelBuilder.Entity("AWork.Business.Models.Country", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("AWork.Business.Models.Course", b =>
                {
                    b.Navigation("AcademicEducations");
                });

            modelBuilder.Entity("AWork.Business.Models.CourseLevel", b =>
                {
                    b.Navigation("Course");
                });

            modelBuilder.Entity("AWork.Business.Models.Entities", b =>
                {
                    b.Navigation("EntityChild");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("AWork.Business.Models.Interview", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AWork.Business.Models.InterviewStatus", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("AWork.Business.Models.InterviewsSchedule", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("AWork.Business.Models.Job", b =>
                {
                    b.Navigation("JobSubscribe");
                });

            modelBuilder.Entity("AWork.Business.Models.JobRequest", b =>
                {
                    b.Navigation("Job");

                    b.Navigation("JobRequestStatus");
                });

            modelBuilder.Entity("AWork.Business.Models.JobSubscribe", b =>
                {
                    b.Navigation("InterviewsSchedules");
                });

            modelBuilder.Entity("AWork.Business.Models.JobTitle", b =>
                {
                    b.Navigation("JobRequest");

                    b.Navigation("JobTitleChild");

                    b.Navigation("JobTitleInteresteds");
                });

            modelBuilder.Entity("AWork.Business.Models.JobTitleLevel", b =>
                {
                    b.Navigation("ProfessionalBackgrounds");
                });

            modelBuilder.Entity("AWork.Business.Models.Language", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("AWork.Business.Models.Location", b =>
                {
                    b.Navigation("InterviewsSchedule");

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("AWork.Business.Models.MaritalStatus", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("AWork.Business.Models.Person", b =>
                {
                    b.Navigation("AcademicEducations");

                    b.Navigation("ContractRequests");

                    b.Navigation("Interviews");

                    b.Navigation("JobRequestStatus");

                    b.Navigation("Jobs");

                    b.Navigation("JobSubscribes");

                    b.Navigation("JobTitleInteresteds");

                    b.Navigation("Languages");

                    b.Navigation("Notifications");

                    b.Navigation("Phones");

                    b.Navigation("ProfessionalBackgrounds");
                });

            modelBuilder.Entity("AWork.Business.Models.Religion", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("AWork.Business.Models.SpecialNeeds", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("AWork.Business.Models.WorkingArea", b =>
                {
                    b.Navigation("ProfessionalBackgrounds");
                });
#pragma warning restore 612, 618
        }
    }
}
