// <auto-generated />
using System;
using AWork.Candidatos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AWork.Infra.Migrations
{
    [DbContext(typeof(CandidateContext))]
    [Migration("20210816201357_AddressCandidate")]
    partial class AddressCandidate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.AcademicEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CourseStatus")
                        .HasColumnType("int");

                    b.Property<string>("CustomCourse")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CourseId");

                    b.ToTable("AcademicEducations");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .HasColumnType("varchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("MaritalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NationalityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PPD")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReligionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecialNeedsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("SpecialNeedsId");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLevelId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.CourseLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseLevelName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CourseLevels");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.JobTitleInterested", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("JobTitleInteresteds");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.JobTitleLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("JobTitleLevels");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.LanguageCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FluencyLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguegePerson");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.MaritalStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatus");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.NotificationForCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Default")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("PhoneType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.ProfessionalBackground", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CurrentJob")
                        .HasColumnType("bit");

                    b.Property<string>("DescriptionJob")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobTitleLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobTitleName")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkingAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobTitleLevelId");

                    b.HasIndex("WorkingAreaId");

                    b.ToTable("ProfessionalBackgrounds");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Religion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.SpecialNeeds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SpecialNeeds");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.WorkingArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("WorkingAreas");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.AcademicEducation", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.Candidate", "Candidate")
                        .WithMany("AcademicEducations")
                        .HasForeignKey("CandidateId")
                        .IsRequired();

                    b.HasOne("AWork.Candidatos.Domain.Models.Course", "Course")
                        .WithMany("AcademicEducations")
                        .HasForeignKey("CourseId")
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Address", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.Candidate", "Candidate")
                        .WithOne("Address")
                        .HasForeignKey("AWork.Candidatos.Domain.Models.Address", "CandidateId")
                        .IsRequired();

                    b.HasOne("AWork.Candidatos.Domain.Models.Country", "Country")
                        .WithMany("Address")
                        .HasForeignKey("CountryId")
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Candidate", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.MaritalStatus", "MaritalStatus")
                        .WithMany("Candidates")
                        .HasForeignKey("MaritalStatusId");

                    b.HasOne("AWork.Candidatos.Domain.Models.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("AWork.Candidatos.Domain.Models.Religion", "Religion")
                        .WithMany("Candidates")
                        .HasForeignKey("ReligionId");

                    b.HasOne("AWork.Candidatos.Domain.Models.SpecialNeeds", "SpecialNeeds")
                        .WithMany("Candidates")
                        .HasForeignKey("SpecialNeedsId");

                    b.OwnsOne("AWork.Core.DomainObjects.Cpf", "CPF", b1 =>
                        {
                            b1.Property<Guid>("CandidateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("CandidateId");

                            b1.ToTable("Candidate");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId");
                        });

                    b.Navigation("CPF");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Nationality");

                    b.Navigation("Religion");

                    b.Navigation("SpecialNeeds");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Course", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.CourseLevel", "CourseLevel")
                        .WithMany("Course")
                        .HasForeignKey("CourseLevelId")
                        .IsRequired();

                    b.Navigation("CourseLevel");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.JobTitle", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.JobTitle", "JobTitleParent")
                        .WithMany("JobTitleChild")
                        .HasForeignKey("JobTitleId");

                    b.Navigation("JobTitleParent");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.JobTitleInterested", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.Candidate", "Candidate")
                        .WithMany("JobTitleInteresteds")
                        .HasForeignKey("CandidateId")
                        .IsRequired();

                    b.HasOne("AWork.Candidatos.Domain.Models.JobTitle", "JobTitle")
                        .WithMany("JobTitleInteresteds")
                        .HasForeignKey("JobTitleId")
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.LanguageCandidate", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.Candidate", "Candidate")
                        .WithMany("Languages")
                        .HasForeignKey("CandidateId")
                        .IsRequired();

                    b.HasOne("AWork.Candidatos.Domain.Models.Language", "Language")
                        .WithMany("Languages")
                        .HasForeignKey("LanguageId")
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.NotificationForCandidate", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.Candidate", "Candidate")
                        .WithMany("Notifications")
                        .HasForeignKey("CandidateId")
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Phone", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.Candidate", "Candidate")
                        .WithMany("Phones")
                        .HasForeignKey("CandidateId")
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.ProfessionalBackground", b =>
                {
                    b.HasOne("AWork.Candidatos.Domain.Models.Candidate", "Candidate")
                        .WithMany("ProfessionalBackgrounds")
                        .HasForeignKey("CandidateId")
                        .IsRequired();

                    b.HasOne("AWork.Candidatos.Domain.Models.JobTitleLevel", "JobTitleLevel")
                        .WithMany("ProfessionalBackgrounds")
                        .HasForeignKey("JobTitleLevelId")
                        .IsRequired();

                    b.HasOne("AWork.Candidatos.Domain.Models.WorkingArea", "WorkingArea")
                        .WithMany("ProfessionalBackgrounds")
                        .HasForeignKey("WorkingAreaId")
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobTitleLevel");

                    b.Navigation("WorkingArea");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Candidate", b =>
                {
                    b.Navigation("AcademicEducations");

                    b.Navigation("Address");

                    b.Navigation("JobTitleInteresteds");

                    b.Navigation("Languages");

                    b.Navigation("Notifications");

                    b.Navigation("Phones");

                    b.Navigation("ProfessionalBackgrounds");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Country", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Course", b =>
                {
                    b.Navigation("AcademicEducations");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.CourseLevel", b =>
                {
                    b.Navigation("Course");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.JobTitle", b =>
                {
                    b.Navigation("JobTitleChild");

                    b.Navigation("JobTitleInteresteds");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.JobTitleLevel", b =>
                {
                    b.Navigation("ProfessionalBackgrounds");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Language", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.MaritalStatus", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.Religion", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.SpecialNeeds", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("AWork.Candidatos.Domain.Models.WorkingArea", b =>
                {
                    b.Navigation("ProfessionalBackgrounds");
                });
#pragma warning restore 612, 618
        }
    }
}
